#!/usr/bin/env bash
# This script displays username, user ID, and home directory from /etc/passwd

while IFS=: read -r username _ user_id _ _ home_dir _
do
  echo "$username:$user_id:$home_dir"
done < /etc/passwd
