#!/usr/bin/env bash
# Parse, group, and sort Apache log data by IP and HTTP code occurrence

awk '{print $1, $9}' apache-access.log | \
sort | uniq -c | sort -nr | \
awk '{printf "%8d %s %s\n", $1, $2, $3}'
