#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely and handles SIGTERM signal

# Trap SIGTERM signal to display custom message
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done

