#!/usr/bin/env bash
# This script displays an infinite message and reacts to SIGTERM signal

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done

